### Create pipeline
POST http://localhost:8080/pipelines
Content-Type: application/json

{
  "pipelineName": "test_pipeline",
  "webhookUrl": "test"
}

### Read pipeline
GET http://localhost:8080/pipelines/4

### Update pipeline
PUT http://localhost:8080/pipelines/4
Content-Type: application/json

{
  "pipelineName": "test_pipeline",
  "webhookUrl": "test3"
}

### Delete pipeline
DELETE http://localhost:8080/pipelines/3

### Add a job
POST http://localhost:8080/webhooks/test
Content-Type: application/json

{
  "payload": {
    "message": "Hello from webhook",
    "value": 123
  }
}
